### ISSUE TITLE
Payment id is not generating after transaction failed

### ISSUE THREAD

**Issue by fazil-augr** [dynamitechetan/razorpay_flutter#11]
payment not showing when transaction failed. But it generating in razor pay. For checking the payment details. It is difficult to find failed transactions details. So write a method to retrieve payed id after transaction failed.

**Comment by dynamitechetan** [comment]
if the transaction is failed why do you need the payment id?

**Comment by sharad-paghadal** [comment]
you won't get payment id if payment is failed, as closing manually is the only option for leaving the payment, you won't needs to have payment id. If payment is failed due to any reason user will still be there at payment page to retry until success. So expecting payment id after failing is not relevant.
