### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "razorpay_plugin":

### ISSUE THREAD

**Issue by SandyAra** [dynamitechetan/razorpay_flutter#16]
[!] CocoaPods could not find compatible versions for pod "razorpay_plugin":
  In Podfile:
    razorpay_plugin (from `.symlinks/plugins/razorpay_plugin/ios`)

Specs satisfying the `razorpay_plugin (from `.symlinks/plugins/razorpay_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by dynamitechetan** [comment]
hey @SandyAra . What swift version are you using. Please make sure you are using latest xcode version and swift5.

**Comment by kapil708** [comment]
hi i am having the same issue.

[!] CocoaPods could not find compatible versions for pod "razorpay_plugin":
  In Podfile:
    razorpay_plugin (from `.symlinks/plugins/razorpay_plugin/ios`)

Specs satisfying the `razorpay_plugin (from `.symlinks/plugins/razorpay_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

And My Swift Version Is This
-----------------------------------
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.5.0

**Comment by kapil708** [comment]
I find a solution I enable swift support for my flutter project and its working.
for more detail see the [link](https://github.com/dynamitechetan/razorpay_flutter/issues/19#issuecomment-495486681)

**Comment by sharad-paghadal** [comment]
@SandyAra does it resolved your problem? If so you can close issue.

**Comment by karansingla-dev** [comment]
@SandyAra  i am still facing this [issue](https://github.com/razorpay/razorpay-flutter/issues/227)

**Comment by karansingla-dev** [comment]
@SandyAra  it's a critical error and because of this release is stuck. Can you provide me time estimation?

**Comment by karansingla-dev** [comment]
https://github.com/razorpay/razorpay-flutter/issues/227#issuecomment-1029967462

@SandyAra @kapil708 @dynamitechetan  any has solution for this issue.

**Comment by haseelrefl** [comment]
platform :ios, '12.0'
use_frameworks!

Adding these two lines to the top of Podfile solved my issue
